### ISSUE TITLE
[Bug : 2D Map Provider] The tile image size do not fit into the map

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#1405] opened 2024-09-13 07:59 UTC
### What happened ?

Hi @wolfgang-ch ,
With using a specific tile url provider, i am getting really strange displays in MTB.
I shared with you by email this url example, but here are the display in MTB.

![image](https://github.com/user-attachments/assets/b5350a5e-a287-41bf-a878-ef597083a498)

or 
![image](https://github.com/user-attachments/assets/69bf0fc1-e9d6-4564-866c-db29c1466e33)

and it should look like 

![image](https://github.com/user-attachments/assets/7185562d-e906-43ca-9f1a-31bc04ef4870)

### Version

24.9

### System

Windows

**Comment by wolfgang-ch** [comment] 2024-09-13 08:31
The problem ist, that the track tiles are 512x512 and the url has not a `@2x` name part. So a mixture of 512x512 and 256x256 map tiles are not yet supported. 

I tested it with a `@2x` tile provider but this is also not yet supported.

In MT 24.9 only a simple `@2x` tile provider is supported

**Comment by wolfgang-ch** [comment] 2024-09-13 16:29
I could fix this by resizing the track image from 512 -> 256 but what is not yet fixed is the use of 4k tile images

![image](https://github.com/user-attachments/assets/47902e1a-ac86-40a7-90bc-0a0829f6e0e2)

**Comment by mff73** [comment] 2024-09-13 17:13
No problem, I don't have 4k display 😂.
You are so perfect, thanks '

**Comment by wolfgang-ch** [comment] 2024-09-14 05:49
It is interresting to see the run to the "Churfürsten"

![image](https://github.com/user-attachments/assets/8b267930-27d3-4cbf-bc78-f0ee31d553cc)

**Comment by wolfgang-ch** [comment] 2024-09-18 05:56
Fixed in 24.9.1

**Closed by wolfgang-ch** 2024-09-18 05:56 UTC
Labels: Bug

**Comment by mff73** [comment] 2024-09-18 12:24
Super, 24.9.1 is working well.
