### ISSUE TITLE
[Bug : 2D Tour Map] [Bug : Tour Chart] Heading Mini Status Window on top of all other programs

### ISSUE THREAD

**Issue by kantrol** [mytourbook/mytourbook#1067] opened 2023-04-15 17:25 UTC
### What happened ?

I do not know how these mini windows (2D Map and Tour Chart) in the heading are called, a screenshot should tell what I mean:
![image](https://user-images.githubusercontent.com/759303/232242046-671ab00a-44f6-4d45-bbdb-00dd096fbcea.png)

MyTourBook window is behind the browser window, but these 2 parts are always sitting over other programs. 
If this matters: Linux Debian, X-Window KDE Plasma 5.27
The browser is only an example, all programs are affected.

### Version

23.3.2

### System

Linux

**Comment by FJBDev** [comment] 2023-04-15 18:21
> ### What happened ?
> 
> I do not know how these mini windows (2D Map and Tour Chart) in the heading are called

They are called **tooltips**

>MyTourBook window is behind the browser window, but these 2 parts are always sitting over other programs.

Duplicate of #1030 & #639

**Comment by wolfgang-ch** [comment] 2023-04-16 04:51
This https://github.com/mytourbook/mytourbook/issues/1030#issuecomment-1476566816 is my standard answer to this endless story. 

I'm aware that this is not the best solution but I didn't find another.

**Closed by wolfgang-ch** 2023-04-16 04:51 UTC
Labels: Bug
