### ISSUE TITLE
[Bug : 3D Map] View doesn't fill the pane

### ISSUE THREAD

**Issue by yiranlus** [mytourbook/mytourbook#1421] opened 2024-11-04 12:08 UTC
### What happened ?

The 3D Map view doesn't fill up the pane, left part of the pane black.

![image](https://github.com/user-attachments/assets/1200eddd-5a3f-4e41-b830-bda928f581aa)

### Version

24.11.0

### System

Windows

**Comment by wolfgang-ch** [comment] 2024-11-04 12:51
This is a duplicate of https://github.com/mytourbook/mytourbook/issues/503

**Closed by wolfgang-ch** 2024-11-04 12:51 UTC
Labels: Bug
